### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by ASKMOUNTAIN**

### CODE REVIEW

**Comment by Toma1O6** [comment]
It looks good now, thank you

**Comment by ASKMOUNTAIN** [comment]
Ok, so now I just need to wait for you to update the mod version and download it again. Then there will be a Chinese translation of perk?

**Comment by Toma1O6** [comment]
yes

**Comment by ASKMOUNTAIN** [comment]
ok，thank you very much！

**Pull request merged**
