### PR TITLE
A Chinese translation of perk

### PR DESCRIPTION
**Pull request by ASKMOUNTAIN**

### CODE REVIEW

**Comment by Toma1O6** [comment]
Please put the file between other localization files

**Comment by ASKMOUNTAIN** [comment]
> 请将文件放在其他本地化文件之间
I adjusted it. Is it right this time

**Comment by ASKMOUNTAIN** [comment]
I changed it. Is it correct this time？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Toma1O6/Guns-RPG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 凌晨5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Toma1O6/Guns-RPG] A Chinese translation of perk (PR #27)





 
Please put the file between other localization files

**Comment by Toma1O6** [comment]
No, this is completely wrong. All you need to do is to include the file in `lang` directory along with other localization files which are already here (there is already chinese translation so you can build on that).
Second - you need to do this on the 1.16.5 branch, no idea why you have decided to select inactive development branch.

**Comment by ASKMOUNTAIN** [comment]
Ok, I tried to submit it again. Is it right this time? I'm sorry this is my first time using github so I'm not very good at it




谈风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Toma1O6/Guns-RPG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 凌晨5:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Toma1O6/Guns-RPG] A Chinese translation of perk (PR #27)





 
No, this is completely wrong. All you need to do is to include the file in lang directory along with other localization files which are already here (there is already chinese translation so you can build on that).
 Second - you need to do this on the 1.16.5 branch, no idea why you have decided to select inactive development branch.

**Pull request closed without merging**
